import type { FastifyInstance } from "fastify";

export function registerHealthCheckerOperatorOverviewMockRoute(
  app: FastifyInstance,
) {
  app.get("/api/health-checker/operator-overview-mock", async () => ({
    service: "sam-health-checker",
    mode: "mock_overview",
    status: "completed",
    version: "0.1.0",
    overview_id: "overview_001",
    scan_summary: {
      source_scan_id: "mock_scan_001",
      source_flow_id: "mock_flow_001",
      source_route: "/api/health-checker/mock-scan-to-review-flow",
      status: "completed",
      checked_at: "2026-06-15T10:00:00.000Z",
      products_checked: 4,
      issues_found: 4,
      proposals_previewed: 4,
      review_items: 4,
      risk_level: "medium",
    },
    issues: [
      {
        issue_id: "issue_001",
        product_sku: "DEMO-001",
        type: "missing_product_image",
        severity: "high",
        status: "open",
        message: "Primary product image is missing.",
      },
      {
        issue_id: "issue_002",
        product_sku: "DEMO-002",
        type: "missing_short_description",
        severity: "medium",
        status: "open",
        message: "Short description is missing.",
      },
      {
        issue_id: "issue_003",
        product_sku: "DEMO-003",
        type: "missing_product_tags",
        severity: "medium",
        status: "open",
        message: "Product tags are missing.",
      },
      {
        issue_id: "issue_004",
        product_sku: "DEMO-004",
        type: "seo_basic_gap",
        severity: "medium",
        status: "open",
        message: "Basic SEO metadata is incomplete.",
      },
    ],
    proposal_previews: [
      {
        proposal_id: "preview_001",
        source_issue_type: "missing_product_image",
        proposal_type: "add_product_image",
        title: "Add missing primary product image",
        current_state: "No primary image is available for the product.",
        proposed_change: "Request a primary product image and attach it after manual approval.",
        risk_level: "high",
        confidence: "high",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
      {
        proposal_id: "preview_002",
        source_issue_type: "missing_short_description",
        proposal_type: "generate_short_description",
        title: "Generate short product description",
        current_state: "Short description is empty.",
        proposed_change: "Prepare a short commercial description draft for operator review.",
        risk_level: "medium",
        confidence: "medium",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
      {
        proposal_id: "preview_003",
        source_issue_type: "missing_product_tags",
        proposal_type: "add_product_tags",
        title: "Add starter tag set",
        current_state: "No product tags are assigned.",
        proposed_change: "Prepare a small tag set for manual approval before publication.",
        risk_level: "medium",
        confidence: "medium",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
      {
        proposal_id: "preview_004",
        source_issue_type: "seo_basic_gap",
        proposal_type: "improve_basic_seo",
        title: "Improve basic SEO metadata",
        current_state: "Basic SEO metadata is incomplete.",
        proposed_change: "Prepare a metadata improvement suggestion for operator review.",
        risk_level: "medium",
        confidence: "medium",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
    ],
    review_queue: [
      {
        review_id: "review_001",
        proposal_id: "preview_001",
        source_issue_type: "missing_product_image",
        proposal_type: "add_product_image",
        current_status: "ready_for_review",
        recommended_action: "approve",
        available_actions: ["approve", "reject", "hold", "needs_more_context"],
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        operator_note: "Image request can proceed after manual confirmation.",
      },
      {
        review_id: "review_002",
        proposal_id: "preview_002",
        source_issue_type: "missing_short_description",
        proposal_type: "generate_short_description",
        current_status: "ready_for_review",
        recommended_action: "request_changes",
        available_actions: [
          "approve",
          "reject",
          "hold",
          "request_changes",
          "needs_more_context",
        ],
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        operator_note: "Description draft needs more commercial tone before approval.",
      },
      {
        review_id: "review_003",
        proposal_id: "preview_003",
        source_issue_type: "missing_product_tags",
        proposal_type: "add_product_tags",
        current_status: "ready_for_review",
        recommended_action: "approve",
        available_actions: ["approve", "reject", "hold", "request_changes"],
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        operator_note: "Starter tags look acceptable for manual approval.",
      },
      {
        review_id: "review_004",
        proposal_id: "preview_004",
        source_issue_type: "seo_basic_gap",
        proposal_type: "improve_basic_seo",
        current_status: "ready_for_review",
        recommended_action: "needs_more_context",
        available_actions: [
          "approve",
          "reject",
          "hold",
          "request_changes",
          "needs_more_context",
        ],
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        operator_note: "More brand-specific context is needed before approval.",
      },
    ],
    approval_policy: {
      human_approval_required: true,
      auto_approval_allowed: false,
      auto_execute_allowed: false,
      bulk_approval_allowed: false,
      write_actions: "disabled",
      default_next_status: "ready_for_review",
    },
    audit_trail_preview: [
      {
        event_type: "scan_started",
        source_endpoint: "/api/health-checker/mock-scan",
        reason: "A mock scan begins the operator overview flow.",
      },
      {
        event_type: "issue_detected",
        source_endpoint: "/api/health-checker/mock-scan",
        reason: "The mock scan identifies the product issues in scope.",
      },
      {
        event_type: "proposal_previewed",
        source_endpoint: "/api/health-checker/mock-proposal-preview",
        reason: "Proposal previews are prepared for operator review.",
      },
      {
        event_type: "operator_review_opened",
        source_endpoint: "/api/health-checker/operator-review-preview",
        reason: "The operator overview presents the review queue.",
      },
      {
        event_type: "proposal_approved",
        source_endpoint: "/api/health-checker/approval-flow-contract",
        reason: "Approval remains human-led and non-executing.",
      },
      {
        event_type: "audit_log_recorded",
        source_endpoint: "/api/health-checker/audit-log-preview",
        reason: "Audit preview shows the decision trace without runtime writes.",
      },
    ],
    safety: {
      database: "not_used",
      woocommerce: "not_connected",
      prisma: "not_used",
      secrets: "not_required",
      write_actions: "disabled",
      auto_execute: "disabled",
      runtime_logging: "disabled",
    },
    future_extension_hooks: [
      {
        hook: "customer_shop_segmentation",
        status: "metadata_only",
        note: "Future grouping by customer or shop segment.",
      },
      {
        hook: "issue_priority",
        status: "metadata_only",
        note: "Future priority ordering for operator focus.",
      },
      {
        hook: "impact_score",
        status: "metadata_only",
        note: "Future estimate of business impact per issue or proposal.",
      },
      {
        hook: "risk_insight",
        status: "metadata_only",
        note: "Future risk framing for review and approval decisions.",
      },
      {
        hook: "support_status",
        status: "metadata_only",
        note: "Future signal for support or escalation handling.",
      },
      {
        hook: "customer_value",
        status: "metadata_only",
        note: "Future value context for prioritizing review work.",
      },
      {
        hook: "operator_roles",
        status: "metadata_only",
        note: "Future role-based review visibility or filtering.",
      },
      {
        hook: "audit_retention",
        status: "metadata_only",
        note: "Future retention policy metadata for audit traces.",
      },
      {
        hook: "approval_history",
        status: "metadata_only",
        note: "Future historical approval context for repeat reviews.",
      },
      {
        hook: "rollback_undo_preparation",
        status: "metadata_only",
        note: "Future metadata for safe undo preparation.",
      },
      {
        hook: "woocommerce_execution_later",
        status: "metadata_only",
        note: "Future execution routing can stay separate from this mock.",
      },
      {
        hook: "ai_proposal_text_later",
        status: "metadata_only",
        note: "Future AI text generation stays outside this read-only mock.",
      },
      {
        hook: "nautilus_cockpit_view_later",
        status: "metadata_only",
        note: "Future cockpit presentation can consume the same overview shape.",
      },
      {
        hook: "nemo_commerce_positioning_later",
        status: "metadata_only",
        note: "Future positioning metadata can be added without changing runtime behavior.",
      },
    ],
    next_step:
      "Next step can be a read-only operator overview panel mapping or a cockpit wireframe.",
  }));
}
