import type { FastifyInstance } from "fastify";

export function registerHealthCheckerOperatorReviewPreviewRoute(
  app: FastifyInstance,
) {
  app.get("/api/health-checker/operator-review-preview", async () => ({
    service: "sam-health-checker",
    mode: "mock_preview",
    status: "completed",
    version: "0.1.0",
    source: "mock-proposal-preview",
    summary: {
      review_items: 4,
      requires_human_review: true,
      auto_approval_allowed: false,
      auto_execute_allowed: false,
      write_actions: "disabled",
    },
    review_queue: [
      {
        review_id: "review_001",
        proposal_id: "preview_001",
        source_issue_type: "missing_product_image",
        proposal_type: "add_product_image",
        title: "Review missing image proposal",
        risk_level: "high",
        confidence: "high",
        current_status: "ready_for_review",
        recommended_action: "approve",
        available_actions: ["approve", "reject", "hold", "needs_more_context"],
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        operator_note: "Image request can proceed after manual confirmation.",
      },
      {
        review_id: "review_002",
        proposal_id: "preview_002",
        source_issue_type: "missing_short_description",
        proposal_type: "generate_short_description",
        title: "Review short description draft",
        risk_level: "medium",
        confidence: "medium",
        current_status: "ready_for_review",
        recommended_action: "request_changes",
        available_actions: [
          "approve",
          "reject",
          "hold",
          "request_changes",
          "needs_more_context",
        ],
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        operator_note: "Description draft needs more commercial tone before approval.",
      },
      {
        review_id: "review_003",
        proposal_id: "preview_003",
        source_issue_type: "missing_product_tags",
        proposal_type: "add_product_tags",
        title: "Review starter tag set",
        risk_level: "medium",
        confidence: "medium",
        current_status: "ready_for_review",
        recommended_action: "approve",
        available_actions: ["approve", "reject", "hold", "request_changes"],
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        operator_note: "Starter tags look acceptable for manual approval.",
      },
      {
        review_id: "review_004",
        proposal_id: "preview_004",
        source_issue_type: "seo_basic_gap",
        proposal_type: "improve_basic_seo",
        title: "Review SEO improvement suggestion",
        risk_level: "medium",
        confidence: "medium",
        current_status: "ready_for_review",
        recommended_action: "needs_more_context",
        available_actions: [
          "approve",
          "reject",
          "hold",
          "request_changes",
          "needs_more_context",
        ],
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        operator_note: "More brand-specific context is needed before approval.",
      },
    ],
    review_policy: {
      human_review_required: true,
      auto_approval_allowed: false,
      auto_execute_allowed: false,
      bulk_approval_allowed: false,
      default_next_status: "ready_for_review",
    },
    safety: {
      database: "not_used",
      woocommerce: "not_connected",
      prisma: "not_used",
      secrets: "not_required",
      write_actions: "disabled",
      auto_execute: "disabled",
    },
    next_step:
      "Next step can be approval-flow contract or review decision mock.",
  }));
}
