import type { FastifyInstance } from "fastify";

export function registerHealthCheckerIssueProposalMappingRoute(
  app: FastifyInstance,
) {
  app.get("/api/health-checker/issue-proposal-mapping", async () => ({
    service: "sam-health-checker",
    mode: "contract",
    status: "available",
    version: "0.1.0",
    mapping_model: {
      source: "issue-classification",
      target: "proposal-contract",
      human_approval_required: true,
      auto_execute_allowed: false,
    },
    mappings: [
      {
        issue_type: "missing_product_image",
        proposal_type: "add_product_image",
        default_priority: "high",
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        risk_level: "high",
        confidence_required: "high",
        notes: "Image additions must stay under manual review before execution.",
      },
      {
        issue_type: "missing_short_description",
        proposal_type: "generate_short_description",
        default_priority: "medium",
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        risk_level: "medium",
        confidence_required: "medium",
        notes: "Generated short descriptions require operator approval.",
      },
      {
        issue_type: "weak_short_description",
        proposal_type: "improve_short_description",
        default_priority: "low",
        requires_human_review: false,
        requires_human_approval: true,
        auto_execute_allowed: false,
        risk_level: "low",
        confidence_required: "medium",
        notes: "Weak copy can be improved, but publication remains manual.",
      },
      {
        issue_type: "missing_long_description",
        proposal_type: "generate_long_description",
        default_priority: "high",
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        risk_level: "high",
        confidence_required: "high",
        notes: "Long-form content proposals need human review before approval.",
      },
      {
        issue_type: "weak_long_description",
        proposal_type: "improve_long_description",
        default_priority: "medium",
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        risk_level: "medium",
        confidence_required: "medium",
        notes: "Quality upgrades remain non-executable until approved.",
      },
      {
        issue_type: "missing_product_tags",
        proposal_type: "add_product_tags",
        default_priority: "medium",
        requires_human_review: false,
        requires_human_approval: true,
        auto_execute_allowed: false,
        risk_level: "medium",
        confidence_required: "medium",
        notes: "Tag proposals may be generated, but not auto-applied.",
      },
      {
        issue_type: "seo_basic_gap",
        proposal_type: "improve_basic_seo",
        default_priority: "medium",
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        risk_level: "medium",
        confidence_required: "medium",
        notes: "SEO changes remain review-based to avoid unintended edits.",
      },
      {
        issue_type: "unknown_product_data_issue",
        proposal_type: "manual_review_required",
        default_priority: "critical",
        requires_human_review: true,
        requires_human_approval: true,
        auto_execute_allowed: false,
        risk_level: "critical",
        confidence_required: "high",
        notes: "Unknown issues must be routed to manual review first.",
      },
    ],
    safety: {
      database: "not_used",
      woocommerce: "not_connected",
      prisma: "not_used",
      secrets: "not_required",
      write_actions: "disabled",
      auto_execute: "disabled",
    },
    next_step:
      "Next step can be mock proposal generation or scan-result-to-proposal preview.",
  }));
}
