import type { FastifyInstance } from "fastify";

export function registerHealthCheckerAuditLogPreviewRoute(
  app: FastifyInstance,
) {
  app.get("/api/health-checker/audit-log-preview", async () => ({
    service: "sam-health-checker",
    mode: "mock_preview",
    status: "completed",
    version: "0.1.0",
    source: "audit-log-contract",
    summary: {
      audit_events_previewed: 7,
      human_decision_events: 3,
      system_events: 4,
      runtime_logging: "disabled",
      database: "not_used",
    },
    audit_trail: [
      {
        event_id: "audit_001",
        event_type: "scan_started",
        timestamp: "2026-06-14T00:00:00.000Z",
        actor_type: "system",
        actor_id: "system",
        scan_id: "mock_scan_001",
        issue_id: null,
        proposal_id: null,
        action: "start",
        previous_status: "idle",
        new_status: "running",
        reason: "A mock scan begins for audit preview purposes.",
        source_endpoint: "/api/health-checker/mock-scan",
        risk_note: "Start events must avoid sensitive runtime payloads.",
      },
      {
        event_id: "audit_002",
        event_type: "issue_detected",
        timestamp: "2026-06-14T00:01:00.000Z",
        actor_type: "system",
        actor_id: "system",
        scan_id: "mock_scan_001",
        issue_id: "issue_001",
        proposal_id: null,
        action: "flag",
        previous_status: "running",
        new_status: "issue_found",
        reason: "A missing product image was detected in the mock trail.",
        source_endpoint: "/api/health-checker/mock-scan",
        risk_note: "Issue traces must remain source-aware and reviewable.",
      },
      {
        event_id: "audit_003",
        event_type: "proposal_previewed",
        timestamp: "2026-06-14T00:02:00.000Z",
        actor_type: "system",
        actor_id: "system",
        scan_id: "mock_scan_001",
        issue_id: "issue_001",
        proposal_id: "preview_001",
        action: "preview",
        previous_status: "issue_found",
        new_status: "preview_ready",
        reason: "A proposal preview is prepared for operator review.",
        source_endpoint: "/api/health-checker/mock-proposal-preview",
        risk_note: "Preview traces should not imply execution or approval.",
      },
      {
        event_id: "audit_004",
        event_type: "operator_review_opened",
        timestamp: "2026-06-14T00:03:00.000Z",
        actor_type: "operator",
        actor_id: "operator_001",
        scan_id: "mock_scan_001",
        issue_id: "issue_001",
        proposal_id: "preview_001",
        action: "open_review",
        previous_status: "preview_ready",
        new_status: "ready_for_review",
        reason: "A human reviewer opens the preview for inspection.",
        source_endpoint: "/api/health-checker/operator-review-preview",
        risk_note: "Operator review traces support accountability and auditability.",
      },
      {
        event_id: "audit_005",
        event_type: "proposal_approved",
        timestamp: "2026-06-14T00:04:00.000Z",
        actor_type: "operator",
        actor_id: "operator_001",
        scan_id: "mock_scan_001",
        issue_id: "issue_001",
        proposal_id: "preview_001",
        action: "approve",
        previous_status: "ready_for_review",
        new_status: "approved",
        reason: "The operator approved the mock proposal preview.",
        source_endpoint: "/api/health-checker/approval-flow-contract",
        risk_note: "Approval does not imply immediate execution.",
      },
      {
        event_id: "audit_006",
        event_type: "execution_blocked",
        timestamp: "2026-06-14T00:05:00.000Z",
        actor_type: "system",
        actor_id: "system",
        scan_id: "mock_scan_001",
        issue_id: "issue_001",
        proposal_id: "preview_001",
        action: "block_execution",
        previous_status: "approved",
        new_status: "blocked",
        reason: "Execution remains blocked because runtime execution is disabled.",
        source_endpoint: "/api/health-checker/approval-flow-contract",
        risk_note: "Blocked execution events must never expose secrets or raw credentials.",
      },
      {
        event_id: "audit_007",
        event_type: "proposal_rejected",
        timestamp: "2026-06-14T00:06:00.000Z",
        actor_type: "operator",
        actor_id: "operator_001",
        scan_id: "mock_scan_001",
        issue_id: "issue_002",
        proposal_id: "preview_002",
        action: "reject",
        previous_status: "ready_for_review",
        new_status: "rejected",
        reason: "A second proposal was rejected during review.",
        source_endpoint: "/api/health-checker/operator-review-contract",
        risk_note: "Rejected decisions should keep operator reasoning traceable.",
      },
    ],
    compliance_preview: {
      gdpr_data_minimization: true,
      avoid_sensitive_raw_data: true,
      operator_traceability: true,
      ai_transparency_ready: true,
      retention_policy_required_later: true,
    },
    safety: {
      database: "not_used",
      woocommerce: "not_connected",
      prisma: "not_used",
      secrets: "not_required",
      write_actions: "disabled",
      runtime_logging: "disabled",
    },
    next_step:
      "Next step can be contract-layer review or route inventory.",
  }));
}
