import type { FastifyInstance } from "fastify";

export function registerHealthCheckerMockProposalPreviewRoute(
  app: FastifyInstance,
) {
  app.get("/api/health-checker/mock-proposal-preview", async () => ({
    service: "sam-health-checker",
    mode: "mock_preview",
    status: "completed",
    version: "0.1.0",
    source_scan_id: "mock_scan_001",
    summary: {
      issues_found: 4,
      proposals_previewed: 4,
      requires_human_approval: true,
      auto_execute_allowed: false,
      write_actions: "disabled",
    },
    proposal_previews: [
      {
        proposal_id: "preview_001",
        source_issue_type: "missing_product_image",
        proposal_type: "add_product_image",
        title: "Add missing primary product image",
        current_state: "No primary image is available for the product.",
        proposed_change: "Request a primary product image and attach it after manual approval.",
        reason: "Products without a main image reduce clarity and conversion quality.",
        risk_level: "high",
        confidence: "high",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
      {
        proposal_id: "preview_002",
        source_issue_type: "missing_short_description",
        proposal_type: "generate_short_description",
        title: "Generate short product description",
        current_state: "Short description is empty.",
        proposed_change: "Prepare a short commercial description draft for operator review.",
        reason: "A short description improves product scannability and merchandising.",
        risk_level: "medium",
        confidence: "medium",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
      {
        proposal_id: "preview_003",
        source_issue_type: "missing_product_tags",
        proposal_type: "add_product_tags",
        title: "Add starter tag set",
        current_state: "No product tags are assigned.",
        proposed_change: "Prepare a small tag set for manual approval before publication.",
        reason: "Tags support filtering, search and internal product grouping.",
        risk_level: "medium",
        confidence: "medium",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
      {
        proposal_id: "preview_004",
        source_issue_type: "seo_basic_gap",
        proposal_type: "improve_basic_seo",
        title: "Improve basic SEO metadata",
        current_state: "Basic SEO metadata is incomplete.",
        proposed_change: "Prepare a metadata improvement suggestion for operator review.",
        reason: "Basic SEO gaps reduce discoverability and consistency across products.",
        risk_level: "medium",
        confidence: "medium",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
    ],
    approval_flow: {
      human_approval_required: true,
      bulk_approval_allowed: false,
      auto_execute_allowed: false,
      default_status: "ready_for_review",
    },
    safety: {
      database: "not_used",
      woocommerce: "not_connected",
      prisma: "not_used",
      secrets: "not_required",
      write_actions: "disabled",
      auto_execute: "disabled",
    },
    next_step:
      "Next step can be proposal preview detail or operator review contract.",
  }));
}
