import type { FastifyInstance } from "fastify";

export function registerHealthCheckerIssueClassificationRoute(
  app: FastifyInstance,
) {
  app.get("/api/health-checker/issue-classification", async () => ({
    service: "sam-health-checker",
    mode: "contract",
    status: "available",
    version: "0.1.0",
    classification_model: {
      issue_types: 8,
      severity_levels: 4,
      confidence_levels: 3,
      action_categories: 4,
    },
    issue_types: [
      {
        type: "missing_product_image",
        label: "Missing Product Image",
        description: "The product has no primary image available.",
        default_severity: "high",
        action_category: "media_fix",
        can_generate_proposal: true,
        requires_human_review: true,
      },
      {
        type: "missing_short_description",
        label: "Missing Short Description",
        description: "The product is missing a short commercial description.",
        default_severity: "medium",
        action_category: "content_improvement",
        can_generate_proposal: true,
        requires_human_review: true,
      },
      {
        type: "weak_short_description",
        label: "Weak Short Description",
        description: "The short description exists but lacks useful quality.",
        default_severity: "low",
        action_category: "content_improvement",
        can_generate_proposal: true,
        requires_human_review: false,
      },
      {
        type: "missing_long_description",
        label: "Missing Long Description",
        description: "The product is missing a detailed long description.",
        default_severity: "high",
        action_category: "content_improvement",
        can_generate_proposal: true,
        requires_human_review: true,
      },
      {
        type: "weak_long_description",
        label: "Weak Long Description",
        description: "The long description exists but is too limited or shallow.",
        default_severity: "medium",
        action_category: "content_improvement",
        can_generate_proposal: true,
        requires_human_review: true,
      },
      {
        type: "missing_product_tags",
        label: "Missing Product Tags",
        description: "The product has no relevant tags assigned.",
        default_severity: "medium",
        action_category: "seo_enrichment",
        can_generate_proposal: true,
        requires_human_review: false,
      },
      {
        type: "seo_basic_gap",
        label: "SEO Basic Gap",
        description: "Basic SEO-related product metadata is incomplete.",
        default_severity: "medium",
        action_category: "seo_enrichment",
        can_generate_proposal: true,
        requires_human_review: true,
      },
      {
        type: "unknown_product_data_issue",
        label: "Unknown Product Data Issue",
        description: "The detected issue does not match a known standard class.",
        default_severity: "critical",
        action_category: "manual_review",
        can_generate_proposal: false,
        requires_human_review: true,
      },
    ],
    severity_levels: ["low", "medium", "high", "critical"],
    confidence_levels: ["low", "medium", "high"],
    action_categories: [
      "content_improvement",
      "media_fix",
      "seo_enrichment",
      "manual_review",
    ],
    safety: {
      database: "not_used",
      woocommerce: "not_connected",
      prisma: "not_used",
      secrets: "not_required",
      write_actions: "disabled",
    },
    next_step:
      "Next step can be a proposal contract or issue-to-proposal mapping route.",
  }));
}
