import type { FastifyInstance } from "fastify";

export function registerHealthCheckerAuditLogContractRoute(
  app: FastifyInstance,
) {
  app.get("/api/health-checker/audit-log-contract", async () => ({
    service: "sam-health-checker",
    mode: "contract",
    status: "available",
    version: "0.1.0",
    audit_model: {
      source: "approval-flow-contract",
      purpose: "track operator decisions and system-generated proposals",
      write_runtime_logs: false,
      database_required_now: false,
      human_decision_trace_required: true,
    },
    audit_events: [
      {
        event_type: "scan_started",
        label: "Scan Started",
        description: "A product scan begins for a target webshop scope.",
        actor_type: "system",
        requires_human_actor: false,
        captures_reason: false,
        captures_before_after: false,
        retention_category: "operational",
        risk_note: "Start events must avoid sensitive runtime payloads.",
      },
      {
        event_type: "scan_completed",
        label: "Scan Completed",
        description: "A product scan finishes and summary results become available.",
        actor_type: "system",
        requires_human_actor: false,
        captures_reason: false,
        captures_before_after: false,
        retention_category: "operational",
        risk_note: "Completion events should store summary-level data only.",
      },
      {
        event_type: "issue_detected",
        label: "Issue Detected",
        description: "A scan identifies a product issue that may need follow-up.",
        actor_type: "system",
        requires_human_actor: false,
        captures_reason: true,
        captures_before_after: false,
        retention_category: "quality",
        risk_note: "Issue traces must remain source-aware and reviewable.",
      },
      {
        event_type: "proposal_previewed",
        label: "Proposal Previewed",
        description: "A proposal preview is generated for review preparation.",
        actor_type: "system",
        requires_human_actor: false,
        captures_reason: false,
        captures_before_after: true,
        retention_category: "proposal",
        risk_note: "Preview traces should not imply execution or approval.",
      },
      {
        event_type: "operator_review_opened",
        label: "Operator Review Opened",
        description: "A human operator opens a proposal review item.",
        actor_type: "operator",
        requires_human_actor: true,
        captures_reason: false,
        captures_before_after: false,
        retention_category: "review",
        risk_note: "Operator review traces support accountability and auditability.",
      },
      {
        event_type: "proposal_approved",
        label: "Proposal Approved",
        description: "A proposal is approved for later controlled execution.",
        actor_type: "operator",
        requires_human_actor: true,
        captures_reason: false,
        captures_before_after: true,
        retention_category: "decision",
        risk_note: "Approval does not imply immediate execution.",
      },
      {
        event_type: "proposal_rejected",
        label: "Proposal Rejected",
        description: "A proposal is rejected during human review.",
        actor_type: "operator",
        requires_human_actor: true,
        captures_reason: true,
        captures_before_after: true,
        retention_category: "decision",
        risk_note: "Rejected decisions should keep operator reasoning traceable.",
      },
      {
        event_type: "proposal_on_hold",
        label: "Proposal On Hold",
        description: "A proposal is placed on hold pending later review.",
        actor_type: "operator",
        requires_human_actor: true,
        captures_reason: true,
        captures_before_after: true,
        retention_category: "decision",
        risk_note: "On-hold state should preserve why execution stayed blocked.",
      },
      {
        event_type: "changes_requested",
        label: "Changes Requested",
        description: "A reviewer requests changes before any approval can happen.",
        actor_type: "operator",
        requires_human_actor: true,
        captures_reason: true,
        captures_before_after: true,
        retention_category: "decision",
        risk_note: "Change requests should track the requested delta at a high level.",
      },
      {
        event_type: "execution_blocked",
        label: "Execution Blocked",
        description: "Execution remains blocked because approval or safety gates are unmet.",
        actor_type: "system",
        requires_human_actor: false,
        captures_reason: true,
        captures_before_after: false,
        retention_category: "safety",
        risk_note: "Blocked execution events must never expose secrets or raw credentials.",
      },
    ],
    required_fields: [
      "event_id",
      "timestamp",
      "actor_type",
      "actor_id",
      "scan_id",
      "issue_id",
      "proposal_id",
      "action",
      "previous_status",
      "new_status",
      "reason",
      "source_endpoint",
    ],
    compliance_notes: {
      gdpr_data_minimization: true,
      avoid_sensitive_raw_data: true,
      operator_traceability: true,
      retention_policy_required_later: true,
      ai_transparency_ready: true,
    },
    safety: {
      database: "not_used",
      woocommerce: "not_connected",
      prisma: "not_used",
      secrets: "not_required",
      write_actions: "disabled",
      runtime_logging: "disabled",
    },
    next_step:
      "Next step can be audit-log preview or decision-record contract.",
  }));
}
