import type { FastifyInstance } from "fastify";

export function registerHealthCheckerMockScanToReviewFlowRoute(
  app: FastifyInstance,
) {
  app.get("/api/health-checker/mock-scan-to-review-flow", async () => ({
    service: "sam-health-checker",
    mode: "mock_flow",
    status: "completed",
    version: "0.1.0",
    flow_id: "mock_flow_001",
    summary: {
      scan_status: "completed",
      issues_found: 4,
      proposals_previewed: 4,
      review_items: 4,
      approval_required: true,
    },
    scan: {
      scan_id: "mock_scan_001",
      checked_at: "2026-06-14T10:00:00.000Z",
      shop: {
        platform: "woocommerce",
        name: "Demo Webshop",
        url: "https://example.test",
      },
      risk_level: "medium",
    },
    issues: [
      {
        issue_id: "issue_001",
        product_sku: "DEMO-001",
        type: "product_image_check",
        message: "Primary product image is missing.",
      },
      {
        issue_id: "issue_002",
        product_sku: "DEMO-002",
        type: "short_description_check",
        message: "Short description is missing.",
      },
      {
        issue_id: "issue_003",
        product_sku: "DEMO-003",
        type: "tag_check",
        message: "Product tags are missing.",
      },
      {
        issue_id: "issue_004",
        product_sku: "DEMO-004",
        type: "long_description_check",
        message: "Long description is too short.",
      },
    ],
    proposal_previews: [
      {
        proposal_id: "preview_001",
        issue_id: "issue_001",
        proposal_type: "add_product_image",
        current_state: "No primary image is available for the product.",
        proposed_change: "Request a primary product image and attach it after manual approval.",
        reason: "Products without a main image reduce clarity and conversion quality.",
        risk_level: "high",
        confidence: "high",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
      {
        proposal_id: "preview_002",
        issue_id: "issue_002",
        proposal_type: "generate_short_description",
        current_state: "Short description is empty.",
        proposed_change: "Prepare a short commercial description draft for operator review.",
        reason: "A short description improves product scannability and merchandising.",
        risk_level: "medium",
        confidence: "medium",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
      {
        proposal_id: "preview_003",
        issue_id: "issue_003",
        proposal_type: "add_product_tags",
        current_state: "No product tags are assigned.",
        proposed_change: "Prepare a small tag set for manual approval before publication.",
        reason: "Tags support filtering, search and internal product grouping.",
        risk_level: "medium",
        confidence: "medium",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
      {
        proposal_id: "preview_004",
        issue_id: "issue_004",
        proposal_type: "improve_basic_seo",
        current_state: "Basic SEO metadata is incomplete.",
        proposed_change: "Prepare a metadata improvement suggestion for operator review.",
        reason: "Basic SEO gaps reduce discoverability and consistency across products.",
        risk_level: "medium",
        confidence: "medium",
        requires_human_approval: true,
        auto_execute_allowed: false,
        default_status: "ready_for_review",
      },
    ],
    review_queue: [
      {
        review_id: "review_001",
        proposal_id: "preview_001",
        source_issue_type: "missing_product_image",
        proposal_type: "add_product_image",
        current_status: "ready_for_review",
        recommended_action: "approve",
        available_actions: ["approve", "reject", "hold", "needs_more_context"],
      },
      {
        review_id: "review_002",
        proposal_id: "preview_002",
        source_issue_type: "missing_short_description",
        proposal_type: "generate_short_description",
        current_status: "ready_for_review",
        recommended_action: "request_changes",
        available_actions: [
          "approve",
          "reject",
          "hold",
          "request_changes",
          "needs_more_context",
        ],
      },
      {
        review_id: "review_003",
        proposal_id: "preview_003",
        source_issue_type: "missing_product_tags",
        proposal_type: "add_product_tags",
        current_status: "ready_for_review",
        recommended_action: "approve",
        available_actions: ["approve", "reject", "hold", "request_changes"],
      },
      {
        review_id: "review_004",
        proposal_id: "preview_004",
        source_issue_type: "seo_basic_gap",
        proposal_type: "improve_basic_seo",
        current_status: "ready_for_review",
        recommended_action: "needs_more_context",
        available_actions: [
          "approve",
          "reject",
          "hold",
          "request_changes",
          "needs_more_context",
        ],
      },
    ],
    approval_policy: {
      human_approval_required: true,
      auto_approval_allowed: false,
      auto_execute_allowed: false,
      bulk_approval_allowed: false,
      write_actions: "disabled",
    },
    audit_trail_preview: [
      {
        event_type: "scan_started",
        source_endpoint: "/api/health-checker/mock-scan",
        reason: "A mock scan begins for the review flow preview.",
      },
      {
        event_type: "issue_detected",
        source_endpoint: "/api/health-checker/mock-scan",
        reason: "The mock scan identifies product issues for follow-up.",
      },
      {
        event_type: "proposal_previewed",
        source_endpoint: "/api/health-checker/mock-proposal-preview",
        reason: "Proposal previews are prepared for operator review.",
      },
      {
        event_type: "operator_review_opened",
        source_endpoint: "/api/health-checker/operator-review-preview",
        reason: "The operator opens the review queue.",
      },
      {
        event_type: "proposal_approved",
        source_endpoint: "/api/health-checker/approval-flow-contract",
        reason: "A proposal can be approved after human review.",
      },
      {
        event_type: "audit_log_recorded",
        source_endpoint: "/api/health-checker/audit-log-preview",
        reason: "Audit preview shows how decision traces would be captured.",
      },
    ],
    safety: {
      database: "not_used",
      woocommerce: "not_connected",
      prisma: "not_used",
      secrets: "not_required",
      write_actions: "disabled",
      auto_execute: "disabled",
    },
    next_step:
      "Next step can be a read-only operator review contract or a scan-to-review mock preview detail.",
  }));
}
