import type { FastifyInstance } from "fastify";

export function registerHealthCheckerProposalContractRoute(
  app: FastifyInstance,
) {
  app.get("/api/health-checker/proposal-contract", async () => ({
    service: "sam-health-checker",
    mode: "contract",
    status: "available",
    version: "0.1.0",
    proposal_model: {
      proposal_types: 8,
      proposal_statuses: 6,
      approval_requirements: 3,
      execution_safety: 5,
    },
    source_provenance_model: {
      source_types: [
        "manufacturer_pdf",
        "xlsx",
        "csv",
        "webshop_existing_data",
        "pim",
        "icecat",
        "manual",
        "ai_generated",
        "source_unknown",
      ],
      required_fields: [
        "sourceType",
        "sourceName",
        "sourceReference",
        "sourceConfidence",
        "evidenceReference",
        "aiGenerated",
        "sourceUnknown",
        "requiresHumanReview",
        "originalField",
        "targetField",
        "oldValue",
        "proposedValue",
      ],
      review_rules: {
        no_proposal_without_source_status: true,
        ai_generated_requires_review: true,
        source_unknown_requires_review: true,
        provenance_required_before_write_rewrite_execution: true,
        no_execution_change_from_contract: true,
      },
    },
    proposal_types: [
      {
        type: "add_product_image",
        label: "Add Product Image",
        description: "Prepare a proposal to add a missing primary product image.",
        source_issue_type: "missing_product_image",
        requires_human_approval: true,
        can_be_auto_generated: false,
        can_be_auto_executed: false,
        default_status: "draft",
        risk_level: "high",
      },
      {
        type: "generate_short_description",
        label: "Generate Short Description",
        description: "Prepare a proposal for a missing short product description.",
        source_issue_type: "missing_short_description",
        requires_human_approval: true,
        can_be_auto_generated: true,
        can_be_auto_executed: false,
        default_status: "draft",
        risk_level: "medium",
      },
      {
        type: "improve_short_description",
        label: "Improve Short Description",
        description: "Prepare a proposal to improve a weak short description.",
        source_issue_type: "weak_short_description",
        requires_human_approval: true,
        can_be_auto_generated: true,
        can_be_auto_executed: false,
        default_status: "draft",
        risk_level: "low",
      },
      {
        type: "generate_long_description",
        label: "Generate Long Description",
        description: "Prepare a proposal for a missing long product description.",
        source_issue_type: "missing_long_description",
        requires_human_approval: true,
        can_be_auto_generated: true,
        can_be_auto_executed: false,
        default_status: "draft",
        risk_level: "high",
      },
      {
        type: "improve_long_description",
        label: "Improve Long Description",
        description: "Prepare a proposal to improve a weak long description.",
        source_issue_type: "weak_long_description",
        requires_human_approval: true,
        can_be_auto_generated: true,
        can_be_auto_executed: false,
        default_status: "draft",
        risk_level: "medium",
      },
      {
        type: "add_product_tags",
        label: "Add Product Tags",
        description: "Prepare a proposal to add missing product tags.",
        source_issue_type: "missing_product_tags",
        requires_human_approval: true,
        can_be_auto_generated: true,
        can_be_auto_executed: false,
        default_status: "draft",
        risk_level: "medium",
      },
      {
        type: "improve_basic_seo",
        label: "Improve Basic SEO",
        description: "Prepare a proposal to improve basic SEO-related metadata.",
        source_issue_type: "seo_basic_gap",
        requires_human_approval: true,
        can_be_auto_generated: true,
        can_be_auto_executed: false,
        default_status: "draft",
        risk_level: "medium",
      },
      {
        type: "manual_review_required",
        label: "Manual Review Required",
        description: "Flag the issue for manual review when no safe proposal fits.",
        source_issue_type: "unknown_product_data_issue",
        requires_human_approval: true,
        can_be_auto_generated: false,
        can_be_auto_executed: false,
        default_status: "ready_for_review",
        risk_level: "critical",
      },
    ],
    proposal_statuses: [
      "draft",
      "ready_for_review",
      "approved",
      "rejected",
      "executed",
      "failed",
    ],
    approval_requirements: {
      human_approval_required: true,
      bulk_approval_allowed: false,
      auto_execute_allowed: false,
    },
    execution_safety: {
      write_actions: "disabled",
      woocommerce: "not_connected",
      database: "not_used",
      prisma: "not_used",
      secrets: "not_required",
    },
    example_proposal: {
      proposal_id: "proposal_mock_001",
      issue_id: "issue_002",
      type: "generate_short_description",
      status: "draft",
      risk_level: "medium",
      summary: "Draft a short product description for manual review.",
      source_provenance: {
        sourceType: "manual",
        sourceName: "operator_review",
        sourceReference: "review_queue.preview_002",
        sourceConfidence: "medium",
        evidenceReference: "mock_scan_001.issue_002",
        aiGenerated: false,
        sourceUnknown: false,
        requiresHumanReview: true,
        originalField: "short_description",
        targetField: "short_description_draft",
        oldValue: "",
        proposedValue: "Draft a short commercial description for manual review.",
      },
    },
    next_step:
      "Next step can be issue-to-proposal mapping or mock proposal generation.",
  }));
}
